import { chromium, expect } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";

const base = process.env.QA_BASE_URL || "http://localhost:3010";
const directory = "/tmp/bao-tin-ui-qa/category-menu";
await mkdir(directory, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.PW_CHROMIUM_PATH ? { executablePath: process.env.PW_CHROMIUM_PATH } : {}) });
const errors = [];
try {
  const page = await browser.newPage();
  page.on("pageerror", (error) => errors.push(error.message));
  const trigger = page.getByRole("button", { name: "Danh mục sản phẩm", exact: true });
  const menu = page.getByRole("menu", { name: "Danh mục sản phẩm", exact: true });
  const panel = page.locator(".bt-category-panel");
  const first = page.getByRole("menuitem", { name: "Phụ kiện bếp", exact: true });
  const last = page.getByRole("menuitem", { name: "Tin công nghệ", exact: true });

  for (const [width, height] of [[1440, 900], [1280, 800], [1024, 768], [1024, 600]]) {
    await page.setViewportSize({ width, height });
    await page.goto(base);
    await expect(page.locator("header[aria-busy]")).toHaveAttribute("aria-busy", "false");
    await page.evaluate(() => document.fonts.ready);
    const sidebar = page.locator(".bt-home-category-sidebar");
    const hero = page.locator(".bt-home-hero-banner");
    await expect(sidebar).toBeVisible();
    await expect(sidebar.getByRole("link")).toHaveCount(8);
    await expect(sidebar.getByRole("heading")).toHaveCSS("font-size", "14px");
    for (const label of await sidebar.locator(".bt-category-item span").all()) {
      await expect(label).toHaveCSS("font-size", "14px");
      await expect(label).toHaveCSS("line-height", "20px");
    }
    const sidebarBounds = await sidebar.boundingBox();
    const heroBounds = await hero.boundingBox();
    expect(sidebarBounds.width).toBe(256);
    expect(sidebarBounds.height).toBe(408);
    expect(heroBounds.y).toBe(sidebarBounds.y);
    expect(heroBounds.height).toBe(sidebarBounds.height);
    expect(heroBounds.x - sidebarBounds.x - sidebarBounds.width).toBe(16);
    await expect(hero.getByRole("combobox")).toHaveCount(0);
    await expect(hero.getByRole("heading")).toHaveCount(0);
    await expect(hero.locator(".bt-home-hero-shade, .bt-home-hero-copy, .bt-home-hero-caption")).toHaveCount(0);
    await expect(page.getByRole("search")).toHaveCount(1);
    for (const label of ["Hàng chính hãng", "Báo giá nhanh", "Hỗ trợ kỹ thuật"]) await expect(page.locator("header").getByText(label, { exact: true })).toBeVisible();
    for (const [name, href] of [["Đăng nhập B2B", "/login"], ["Nhận tư vấn", "/contact#zalo"], ["Xem catalog", "/catalog"]]) {
      const link = page.locator("header").getByRole("link", { name, exact: true });
      await expect(link).toBeVisible();
      await expect(link).toHaveAttribute("href", href);
      expect(await link.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
    }
    await page.getByRole("button", { name: "Chọn slide 2", exact: true }).click();
    await expect(hero.locator('img[data-active="true"]')).toHaveAttribute("src", "/images/hero/cabinet-lighting-hd.jpg");
    await expect(hero.getByRole("link")).toHaveAttribute("href", "/category/led-tu-ke");
    await expect(page.getByRole("button", { name: "Chọn slide 2", exact: true })).toHaveAttribute("aria-pressed", "true");
    expect((await hero.boundingBox()).height).toBe(heroBounds.height);
    await page.getByRole("button", { name: "Ảnh trước", exact: true }).click();
    await expect(page.getByRole("button", { name: "Chọn slide 1", exact: true })).toHaveAttribute("aria-pressed", "true");
    await hero.locator('img[data-active="true"]').evaluate((image) => image.decode());
    await expect(hero.locator('img[data-active="true"]')).toHaveCSS("opacity", "1");
    await page.screenshot({ path: `${directory}/${width}x${height}-home-sidebar.png` });
    const headerSearch = page.locator("header").getByRole("combobox");
    await headerSearch.fill("ban le");
    const suggestions = page.locator("header").getByRole("listbox");
    await expect(suggestions).toBeVisible();
    const suggestionsBounds = await suggestions.boundingBox();
    const point = { x: suggestionsBounds.x + 20, y: Math.min(height - 20, suggestionsBounds.y + suggestionsBounds.height - 4) };
    expect(await page.evaluate(({ x, y }) => document.elementFromPoint(x, y)?.closest('[role="listbox"]')?.id, point)).toBe(await suggestions.getAttribute("id"));
    if (width === 1440) await page.screenshot({ path: `${directory}/header-search-suggestions.png` });
    await headerSearch.press("Escape");
    await headerSearch.fill("");
    await headerSearch.press("Escape");
    await trigger.click();
    await expect(menu).toBeVisible();
    await expect(menu.getByRole("menuitem")).toHaveCount(11);
    await expect(trigger).toBeFocused();
    await expect(first.locator("span")).toHaveCSS("font-size", "16px");
    await expect(first.locator("span")).toHaveCSS("font-weight", "500");
    await expect(panel).toHaveCSS("opacity", "1");
    const bounds = await panel.boundingBox();
    expect(bounds.width).toBe(320);
    expect(bounds.y + bounds.height).toBeLessThanOrEqual(height - 16);
    const scrolling = await menu.evaluate((element) => element.scrollHeight > element.clientHeight + 1);
    expect(scrolling).toBe(height === 600);
    await page.getByRole("menuitem", { name: "Bản lề", exact: true }).hover();
    await page.screenshot({ path: `${directory}/${width}x${height}.png` });
    await trigger.click();
    await expect(menu).toHaveCount(0);
    await expect(panel).toHaveCSS("opacity", "0");

    await trigger.press("ArrowDown");
    await expect(first).toBeFocused();
    await page.keyboard.press("ArrowUp");
    await expect(last).toBeFocused();
    await page.keyboard.press("Home");
    await expect(first).toBeFocused();
    await page.keyboard.press("End");
    await expect(last).toBeFocused();
    await expect(page.locator(".bt-category-heading")).toBeInViewport();
    await page.keyboard.press("Escape");
    await expect(trigger).toBeFocused();
    await trigger.press("ArrowUp");
    await expect(last).toBeFocused();
    await page.keyboard.press("Tab");
    await expect(menu).toHaveCount(0);
    await expect(page.locator('header nav[aria-label="Danh mục sản phẩm"]').getByRole("link").first()).toBeFocused();
    await trigger.click();
    await page.mouse.click(width - 30, height - 30);
    await expect(menu).toHaveCount(0);
    await expect(trigger).toBeFocused();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }

  await page.setViewportSize({ width: 1440, height: 900 });
  const sidebarLinks = page.locator(".bt-home-category-sidebar").getByRole("link");
  await sidebarLinks.first().focus();
  await page.keyboard.press("Tab");
  await expect(sidebarLinks.nth(1)).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(page).toHaveURL(`${base}/category/led-tu-ke`, { timeout: 30000 });
  await expect(page.locator("main h1")).toHaveText("LED tủ/kệ", { timeout: 30000 });
  await expect(page.locator(".bt-home-category-sidebar")).toHaveCount(0);
  await page.goto(base);
  await expect(page.locator("header[aria-busy]")).toHaveAttribute("aria-busy", "false");
  await trigger.click();
  await page.getByRole("menuitem", { name: "Bản lề", exact: true }).click();
  await expect(page).toHaveURL(`${base}/category/ban-le`, { timeout: 30000 });
  await expect(page.locator("main h1")).toHaveText("Bản lề", { timeout: 30000 });
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await trigger.click();
  await expect(page.getByRole("menuitem", { name: "Bản lề", exact: true })).toHaveAttribute("aria-current", "page");
  await expect(panel).toHaveCSS("opacity", "1");
  await page.evaluate(async () => { await document.fonts.ready; await Promise.all(Array.from(document.images).map((image) => image.decode().catch(() => {}))); });
  await page.screenshot({ path: `${directory}/active-category.png` });
  await page.locator("header").getByRole("combobox").first().click();
  await expect(menu).toHaveCount(0);
  await page.keyboard.press("Escape");

  await page.emulateMedia({ reducedMotion: "reduce" });
  await trigger.press("Enter");
  await expect(first).toBeFocused();
  const duration = await panel.evaluate((element) => parseFloat(getComputedStyle(element).transitionDuration));
  expect(duration).toBeLessThan(0.001);
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.setViewportSize({ width: 1440, height: 900 });
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await page.goto(base);
  await expect(page.locator("header[aria-busy]")).toHaveAttribute("aria-busy", "false");
  const imageLink = page.locator(".bt-home-hero-link");
  await imageLink.focus();
  await imageLink.press("ArrowRight");
  await expect(page.getByRole("button", { name: "Chọn slide 2", exact: true })).toHaveAttribute("aria-pressed", "true");
  await imageLink.press("ArrowLeft");
  await expect(page.getByRole("button", { name: "Chọn slide 1", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Chọn slide 2", exact: true }).click();
  await imageLink.click();
  await expect(page).toHaveURL(`${base}/category/led-tu-ke`, { timeout: 30000 });
  await expect(page.locator("main h1")).toHaveText("LED tủ/kệ", { timeout: 30000 });
  for (const [width, height] of [[768, 1024], [390, 844], [320, 812]]) {
    await page.setViewportSize({ width, height });
    await page.goto(base);
    await expect(page.locator("header[aria-busy]")).toHaveAttribute("aria-busy", "false");
    await expect(page.locator(".bt-home-category-sidebar")).toBeHidden();
    await expect(page.getByRole("search")).toHaveCount(1);
    const hero = page.locator(".bt-home-hero-banner");
    await expect(hero.getByRole("combobox")).toHaveCount(0);
    const bounds = await hero.boundingBox();
    expect(Math.abs(bounds.width / bounds.height - 16 / 7)).toBeLessThan(0.01);
    for (const name of ["Đăng nhập B2B", "Nhận tư vấn", "Xem catalog"]) await expect(page.locator("header").getByRole("link", { name, exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Chọn slide 2", exact: true }).click();
    await expect(page.getByRole("button", { name: "Chọn slide 2", exact: true })).toHaveAttribute("aria-pressed", "true");
    await hero.locator('img[data-active="true"]').evaluate((image) => image.decode());
    await expect(hero.locator('img[data-active="true"]')).toHaveCSS("opacity", "1");
    const touchLink = hero.getByRole("link");
    await touchLink.dispatchEvent("pointerdown", { pointerType: "touch", clientX: bounds.x + bounds.width - 60, clientY: bounds.y + 50 });
    await touchLink.dispatchEvent("pointerup", { pointerType: "touch", clientX: bounds.x + 60, clientY: bounds.y + 50 });
    await touchLink.evaluate((element) => element.click());
    await expect(page).toHaveURL(`${base}/`);
    await expect(page.getByRole("button", { name: "Chọn slide 3", exact: true })).toHaveAttribute("aria-pressed", "true");
    await page.getByRole("button", { name: "Chọn slide 2", exact: true }).click();
    await expect(hero.locator('img[data-active="true"]')).toHaveCSS("opacity", "1");
    await page.evaluate(() => document.fonts.ready);
    const promises = await page.locator(".bt-header-promises span").evaluateAll((elements) => elements.map((element) => {
      const bounds = element.getBoundingClientRect();
      return { left: bounds.left, right: bounds.right };
    }));
    expect(promises.every((bounds, index) => bounds.left >= 0 && bounds.right <= width && (!index || bounds.left >= promises[index - 1].right))).toBe(true);
    await page.screenshot({ path: `${directory}/${width}-home.png` });
    await page.getByRole("button", { name: "Mở menu", exact: true }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await page.screenshot({ path: `${directory}/${width}-mobile.png` });
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  expect(errors).toEqual([]);
  const report = { desktopViewports: 4, mobileViewports: 3, sidebarAndSlider: true, imageOnlyHero: true, headerServices: true, issues: errors, passed: true };
  await writeFile(`${directory}/report.json`, JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
} finally {
  await browser.close();
}
