import { chromium, expect } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";

const base = process.env.QA_BASE_URL || "http://localhost:3000";
const pass = process.env.QA_PASS || "pass-1";
const directory = `/tmp/bao-tin-ui-qa/${pass}`;
await mkdir(directory, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.PW_CHROMIUM_PATH ? { executablePath: process.env.PW_CHROMIUM_PATH } : {}) });
const issues = [];
let flowOrder;
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await context.newPage();
  await page.goto(`${base}/products/ban-le-giam-chan-hafele`);
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Bản lề");
  await page.getByRole("spinbutton", { name: "Số lượng", exact: true }).fill("2.8");
  await expect(page.getByRole("spinbutton", { name: "Số lượng", exact: true })).toHaveValue("2");
  await page.getByRole("spinbutton", { name: "Số lượng", exact: true }).fill("2");
  await page.getByRole("button", { name: "Thêm vào giỏ hàng", exact: true }).click();
  await page.getByRole("button", { name: "Yêu thích", exact: true }).click();
  await page.goto(`${base}/cart`);
  await expect(page.getByRole("heading", { name: "Giỏ hàng", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("spinbutton").first()).toHaveValue("2");
  await page.getByLabel("Mã khuyến mãi").fill("INVALID");
  await page.getByRole("button", { name: "Áp dụng", exact: true }).click();
  await expect(page.locator("main").getByRole("alert")).toContainText("không hợp lệ");
  await page.getByLabel("Mã khuyến mãi").fill("BAOTIN10");
  await page.getByRole("button", { name: "Áp dụng", exact: true }).click();
  await expect(page.getByText("Đã áp dụng BAOTIN10", { exact: false })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("baotin-commerce-v1")).coupon)).toBe("BAOTIN10");
  await page.getByRole("button", { name: "Bỏ mã", exact: true }).click();
  await page.goto(`${base}/checkout`);
  await page.getByRole("button", { name: "Tiếp tục", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Thông tin người nhận" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Phương thức nhận hàng" })).toHaveCount(0);
  await page.getByLabel("Họ và tên", { exact: false }).fill("Khách kiểm tra");
  await page.getByLabel("Số điện thoại", { exact: false }).fill("0901234567");
  await page.getByLabel("Email", { exact: true }).fill("qa@example.com");
  await page.getByLabel("Tỉnh/Thành phố", { exact: false }).selectOption("Gia Lai");
  await page.getByLabel("Quận/Huyện", { exact: false }).fill("Quy Nhơn");
  await page.getByLabel("Phường/Xã", { exact: false }).fill("Trần Phú");
  await page.getByLabel("Địa chỉ", { exact: false }).fill("123 Đường ABC");
  await page.getByRole("button", { name: "Tiếp tục", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Phương thức nhận hàng" })).toBeVisible();
  await page.getByRole("button", { name: "Tiếp tục", exact: true }).click();
  await expect(page.getByRole("radio", { name: "Thanh toán công nợ B2B", exact: true })).toHaveCount(0);
  await page.locator("main").getByRole("checkbox").check();
  await page.getByRole("button", { name: "Đặt hàng", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Đặt hàng thành công", exact: true })).toBeVisible();
  flowOrder = await page.evaluate(() => JSON.parse(localStorage.getItem("baotin-commerce-v1")).orders[0]);
  expect(flowOrder.total).toBe(86000);
  expect(flowOrder.status).toBe("Chờ xác nhận");
  await page.getByRole("link", { name: "Xem đơn hàng", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText(flowOrder.id);
  await page.goto(`${base}/account`);
  await expect(page.getByRole("heading", { name: "Đăng nhập tài khoản B2B", exact: true })).toBeVisible();
  await page.goto(`${base}/login`);
  await page.locator('input[name="identity"]').fill("qa@example.com");
  await page.locator('input[name="password"]').fill("preview123");
  await page.getByRole("button", { name: "Đăng nhập", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Xin chào");
  await page.goto(`${base}/products/ban-le-giam-chan-hafele`);
  await expect(page.getByText("Giá B2B", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Xem ảnh 2", exact: true }).click();
  await expect(page.locator('img[fetchpriority="high"]')).toHaveAttribute("src", "/images/catalog/hinge-hd.jpg");
  await page.getByRole("button", { name: "Phóng to ảnh", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("tab", { name: "Mô tả sản phẩm", exact: true }).focus();
  await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("tab", { name: "Tài liệu / Hướng dẫn", exact: true })).toHaveAttribute("aria-selected", "true");
  await page.goto(`${base}/account/company`);
  await page.getByLabel("Mã số thuế").fill("4101234567");
  await page.getByLabel("Địa chỉ công ty").fill("123 Nguyễn Huệ, Quy Nhơn");
  await page.getByLabel("Số điện thoại", { exact: false }).fill("0901234567");
  await page.getByRole("button", { name: "Lưu thông tin", exact: true }).click();
  await page.reload();
  await expect(page.getByLabel("Mã số thuế")).toHaveValue("4101234567");
  await expect(page.getByLabel("Địa chỉ công ty")).toHaveValue("123 Nguyễn Huệ, Quy Nhơn");
  await page.goto(`${base}/account/addresses`);
  await page.getByRole("button", { name: "Thêm địa chỉ", exact: true }).click();
  await page.getByRole("dialog").getByLabel("Địa chỉ đầy đủ", { exact: false }).fill("123 Nguyễn Huệ, Quy Nhơn");
  await page.getByRole("button", { name: "Lưu địa chỉ", exact: true }).click();
  await page.reload();
  await expect(page.getByText("123 Nguyễn Huệ, Quy Nhơn", { exact: false })).toBeVisible();
  await page.goto(`${base}/account/orders/DH20260928001`);
  await page.getByRole("button", { name: "Đặt lại đơn này", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Giỏ hàng", exact: true })).toBeVisible();
  await page.goto(`${base}/search?q=ray%20450`);
  await expect(page.locator(".bt-product-card").first()).toBeVisible();
  await page.goto(`${base}/category/phu-kien-bep`);
  await expect(page.getByRole("heading", { name: "Phụ kiện bếp", exact: true })).toBeVisible();
  await expect(page.locator('main > div img[width="1280"][height="180"]')).toHaveCount(0);
  await page.getByRole("checkbox", { name: "Hafele", exact: true }).check();
  expect(await page.locator(".bt-product-card").count()).toBeGreaterThan(0);
  await page.getByRole("button", { name: "Dạng danh sách", exact: true }).click();
  await expect(page.getByRole("button", { name: "Dạng danh sách", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Xóa bộ lọc", exact: true }).click();
  await page.locator("main").getByRole("button", { name: "2", exact: true }).click();
  await expect(page.locator(".bt-product-card")).toHaveCount(3);
  await page.goto(`${base}/`);
  const homeProducts = page.getByRole("region", { name: "Danh sách sản phẩm", exact: true });
  await expect(homeProducts).toHaveCount(0);
  await expect(page.locator("[data-category-products]")).toHaveCount(5);
  const categoryMenu = page.getByRole("button", { name: "Danh mục sản phẩm", exact: true });
  await categoryMenu.focus();
  await categoryMenu.press("ArrowDown");
  await expect(page.getByRole("menuitem", { name: "Phụ kiện bếp", exact: true })).toBeFocused();
  await page.keyboard.press("ArrowDown");
  await expect(page.getByRole("menuitem", { name: "LED tủ/kệ", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(categoryMenu).toBeFocused();
  await page.getByRole("button", { name: "Sản phẩm tiếp theo", exact: true }).click();
  await page.waitForFunction(() => document.querySelector(".grid-flow-col").scrollLeft > 50);
  await page.getByRole("button", { name: "Thường mua", exact: true }).click();
  await expect(page.locator(".grid-flow-col .bt-product-card").first()).toContainText("Kẹp kính inox");
  await page.getByRole("button", { name: "Bán chạy", exact: true }).click();
  await page.getByRole("button", { name: "Chọn slide 2", exact: true }).click();
  await expect(page.getByRole("button", { name: "Chọn slide 2", exact: true })).toHaveAttribute("aria-pressed", "true");
  const search = page.getByRole("combobox", { name: "Tìm sản phẩm, mã hàng, thương hiệu", exact: true }).first();
  await search.fill("ray");
  await expect(page.getByRole("listbox").getByRole("option").first()).toContainText("108.000");
  await search.press("ArrowDown");
  await search.press("Enter");
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Ray");
  await page.goto(`${base}/checkout`);
  await expect(page.getByLabel("Số điện thoại", { exact: false })).toHaveValue("0901234567");
  await page.getByLabel("Tỉnh/Thành phố", { exact: false }).selectOption("Gia Lai");
  await page.getByLabel("Quận/Huyện", { exact: false }).fill("Quy Nhơn");
  await page.getByLabel("Phường/Xã", { exact: false }).fill("Trần Phú");
  await page.getByLabel("Địa chỉ", { exact: false }).fill("123 Nguyễn Huệ");
  await page.getByRole("button", { name: "Tiếp tục", exact: true }).click();
  await page.getByRole("radio", { name: /Nhận tại cửa hàng/ }).check();
  await page.getByRole("button", { name: "Tiếp tục", exact: true }).click();
  await page.getByRole("radio", { name: "Thanh toán công nợ B2B", exact: true }).check();
  await page.locator("main").getByRole("checkbox").check();
  await page.getByRole("button", { name: "Đặt hàng", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Đặt hàng thành công", exact: true })).toBeVisible();
  const b2bOrder = await page.evaluate(() => JSON.parse(localStorage.getItem("baotin-commerce-v1")).orders[0]);
  expect(b2bOrder.b2b).toBe(true);
  expect(b2bOrder.shipping).toBe(0);
  expect(b2bOrder.total).toBe(50000);
  expect(b2bOrder.status).toBe("Chờ xác nhận");
  await page.goto(`${base}/account`);
  await page.getByRole("button", { name: "Đăng xuất", exact: true }).click();
  await page.goto(`${base}/register`);
  await page.getByLabel("Họ và tên", { exact: false }).fill("Khách hàng mới");
  await page.getByLabel("Tên công ty / Xưởng nội thất", { exact: false }).fill("Xưởng thử nghiệm");
  await page.getByLabel("Số điện thoại", { exact: false }).fill("0901234567");
  await page.getByLabel("Email", { exact: false }).first().fill("new@example.com");
  await page.locator('input[name="password"]').fill("preview123");
  await page.locator("main").getByRole("checkbox").check();
  await page.getByRole("button", { name: "Đăng ký tài khoản", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Khách hàng mới");
  const newCustomer = await page.evaluate(() => JSON.parse(localStorage.getItem("baotin-customer")));
  expect(newCustomer.creditLimit).toBe(0);
  expect(newCustomer.status).toBe("pending");
  await page.goto(`${base}/account/orders`);
  await expect(page.getByRole("heading", { name: "Chưa có đơn hàng phù hợp" })).toBeVisible();
  await page.getByRole("button", { name: "Đăng xuất", exact: true }).click();
  await page.locator('input[name="identity"]').fill("0901234567");
  await page.locator('input[name="password"]').fill("preview123");
  await page.getByRole("button", { name: "Đăng nhập", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Khách hàng mới");
  const restoredCustomer = await page.evaluate(() => JSON.parse(localStorage.getItem("baotin-customer")));
  expect(restoredCustomer.creditLimit).toBe(0);
  expect(restoredCustomer.status).toBe("pending");
  await context.close();
  console.log("Functional flow passed: cart persistence, coupons, validation, guest/B2B checkout, gallery, profile/address persistence, registration, reorder, filters, keyboard search/navigation.");

  const customer = { id: "qa@example.com", name: "Minh Anh", email: "qa@example.com", phone: "0901234567", company: "Nội thất Minh Anh", status: "active", creditLimit: 50000000, debt: 12400000, role: "b2b" };
  const store = { cart: [{ productId: "311.72.501", quantity: 2 }, { productId: "433.02.450", quantity: 1 }], favorites: ["311.72.501", "LED-12V-8W"], orders: [flowOrder], coupon: "" };
  const publicRoutes = ["/", "/category/phu-kien-bep", "/category/ban-le", "/search?q=ray%20450", "/search?q=khong-co-san-pham", "/products/ban-le-giam-chan-hafele", "/cart", "/checkout", `/order/success?id=${flowOrder.id}`, `/order/${flowOrder.id}`, "/login", "/register", "/brand/hafele", "/promotions", "/guides", "/guides/chon-ban-le-theo-loai-canh", "/wishlist", "/contact", "/catalog", "/404"];
  const accountRoutes = ["/account", "/account/orders", "/account/orders/DH20260928001", "/account/products", "/account/favorites", "/account/company", "/account/addresses", "/account/credit", "/account/settings"];
  for (const [width, height] of [[1440, 900], [1280, 800], [1024, 768], [768, 1024], [390, 844]]) {
    const context = await browser.newContext({ viewport: { width, height } });
    await context.addInitScript(({ store }) => { if (!localStorage.getItem("qa-seeded")) { localStorage.setItem("baotin-commerce-v1", JSON.stringify(store)); localStorage.setItem("qa-seeded", "1"); } }, { store });
    const page = await context.newPage();
    for (const [index, route] of [...publicRoutes, ...accountRoutes].entries()) {
      const errors = [];
      const handler = (error) => errors.push(error.message);
      page.on("pageerror", handler);
      if (index === publicRoutes.length) await page.evaluate((customer) => localStorage.setItem("baotin-customer", JSON.stringify(customer)), customer);
      try {
        const response = await page.goto(base + route, { waitUntil: "domcontentloaded" });
        if (response.status() >= 400 && !(route === "/404" && response.status() === 404)) issues.push({ width, route, status: response.status() });
        await page.locator("main").first().waitFor();
        await expect(page.locator("header")).toHaveAttribute("aria-busy", "false");
        if (["/wishlist", "/account/favorites"].includes(route)) await expect(page.locator(".bt-product-card")).toHaveCount(2);
        await page.evaluate(async () => { await document.fonts.ready; document.querySelectorAll("img").forEach((image) => image.loading = "eager"); });
        await page.waitForFunction(() => [...document.images].every((image) => image.complete), undefined, { timeout: 10000 }).catch(() => {});
        const state = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth + 1, width: document.documentElement.scrollWidth, header: document.querySelectorAll("header").length, footer: document.querySelectorAll("footer").length, broken: [...document.images].filter((image) => image.complete && image.naturalWidth === 0).map((image) => image.src) }));
        if (state.overflow || state.header !== 1 || state.footer !== 1 || state.broken.length || errors.length) issues.push({ width, route, ...state, errors });
        await page.screenshot({ path: `${directory}/${width}-${route.replace(/[^a-zA-Z0-9]+/g, "-").slice(0, 95)}.png`, fullPage: true });
      } catch (error) { issues.push({ width, route, error: error.message }); }
      page.off("pageerror", handler);
    }
    if (width === 390) {
      await page.goto(`${base}/category/phu-kien-bep`);
      await page.getByRole("button", { name: /Bộ lọc/ }).click();
      await expect(page.getByRole("dialog")).toBeVisible();
      await page.screenshot({ path: `${directory}/390-filter-sheet.png` });
      await page.getByRole("button", { name: "Đóng", exact: true }).click();
      await page.getByRole("button", { name: "Mở menu", exact: true }).click();
      await expect(page.getByRole("dialog")).toBeVisible();
      await page.screenshot({ path: `${directory}/390-navigation.png` });
      await page.getByRole("button", { name: "Đóng", exact: true }).click();
      await page.goto(`${base}/`);
      await page.getByRole("combobox").first().focus();
      await expect(page.getByRole("dialog")).toBeVisible();
      await page.getByRole("dialog").getByRole("combobox").fill("ray");
      await page.screenshot({ path: `${directory}/390-search-overlay.png` });
      await page.keyboard.press("Escape");
      await expect(page.getByRole("dialog")).toHaveCount(0);
      await page.getByRole("button", { name: "Mở menu", exact: true }).focus();
      await page.getByRole("combobox").first().focus();
      await expect(page.getByRole("dialog")).toBeVisible();
      await page.getByRole("dialog").getByRole("combobox").press("ArrowDown");
      await page.keyboard.press("Enter");
      await expect(page.getByRole("heading", { level: 1 })).toContainText("Ray");
    }
    await context.close();
    console.log(`Visual capture complete: ${width}x${height}`);
  }
  await writeFile(`${directory}/report.json`, JSON.stringify({ pass, routes: 29, viewports: 5, captures: 145, issues }, null, 2));
  console.log(JSON.stringify({ pass, issues, screenshots: directory }));
  if (issues.length) process.exitCode = 1;
} finally { await browser.close(); }
